version: "3.6"
x-logging: &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: lineblocs-app-nginx-proxy
    logging: *default-logging
    ports:
      - "80:80"
    environment:
      - TRUST_DOWNSTREAM_PROXY=true
      - DHPARAM_GENERATION=false
      - HTTPS_METHOD=nohttps
    networks:
      - lineblocs_internal_app
    profiles:
      - enable_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  editor:
    # use image from dockerhub. Using node 11.10.1
    image: node-editor
    build:
      context: .
      dockerfile: Dockerfile
    # Please choose, use block of "volumes" or "develop"
    # volumes:
    #   - ..:/app
    develop:
      watch:
        - action: sync
          path: ..
          target: /app
          ignore:
            - dev/docker-compose.yaml
            - dev/Dockerfile
        - action: sync+restart
          path: ./entrypoint.sh
          target: /app/dev/entrypoint.sh
        - action: sync+restart
          path: ../package.json
          target: /app/package.json
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./docker-compose.yaml
        - action: rebuild
          path: ./.env  
    logging: *default-logging
    working_dir: /app
    container_name: lineblocs-editor
    restart: unless-stopped
    ports:
     - ${EDITOR_PORT_HOST}:9000
    entrypoint:
      sh -c "
        npm config set unsafe-perm=true;
        npm install;
        npm install -g install gulp@3.9.1;
        npm install -g install node-sass@4.13.0 --unsafe-perm ;
        npm install -g install bower@1.8.8 ;
        ./dev/entrypoint.sh ;
      "
    environment:
      - DEPLOYMENT_DOMAIN=${DEPLOYMENT_DOMAIN}
      - VIRTUAL_HOST=editor.${DEPLOYMENT_DOMAIN}
      - VIRTUAL_PORT=9000
    networks:
      - lineblocs_internal_app
networks:
  lineblocs_internal_app: